### ISSUE TITLE
CSS Quebrado 7.2

### ISSUE THREAD

**Issue by cortezfelipe** [bjverde/adianti-theme#6]
Reinaldo 
Fui testar o tema formdin , porem somente tenho a versão 7.2 do template ele quebrou o layout 

![image](https://user-images.githubusercontent.com/7336918/85130414-44fc6f00-b20b-11ea-8471-94276edfdf86.png)

Sabe o motivo? ou vc tem a versão 7.1 para eu testar ?

**Comment by cortezfelipe** [comment]
aqui , obrigado !!!
https://github.com/bjverde/adianti-template

**Comment by bjverde** [comment]
@cortezfelipe  valeu verificar no Adianti 7.2 e ver o que está faltando !!

**Comment by bjverde** [comment]
@cortezfelipe , coloquei as instruções dos temas do FormDin

***Tema FormDin - Horizontal***
https://github.com/bjverde/adianti-theme/blob/master/documents/framework_puro/bootstrap_theme_formdin.md
![Theme_formdin](https://raw.githubusercontent.com/bjverde/adianti-theme/master/documents/img/theme_formdin.png)




***Tema FormDin - Vertical***
https://github.com/bjverde/adianti-theme/blob/master/documents/framework_puro/bootstrap_theme_formdin.md
![Theme_formdin](https://raw.githubusercontent.com/bjverde/adianti-theme/master/documents/img/theme_formdinv.png)
